api/NinosConValorAPI/Data/Repository/INCVRepository.cs, api/NinosConValorAPI/Data/Repository/NCVRepository.cs, api/UnitTests/NCVRepositoryUT/FixedAssetUT.cs
Mostrar un activo fijo en Repository con pruebas incluídas
=> Show fixed asset

api/NinosConValorAPI/Controllers/FixedAssetsController.cs, api/UnitTests/ControllersUT/FixedAssetControllerUT.cs
My credentials are very good :)
=> Show fixed asset continuation Controllers

api/NinosConValorAPI/AutomapperProfile.cs, api/NinosConValorAPI/Controllers/HealthReportsController.cs, api/NinosConValorAPI/Data/Entity/HealthReportEntity.cs, api/NinosConValorAPI/Data/Entity/KidEntity.cs, api/NinosConValorAPI/Data/NCV_DBContext.cs, api/NinosConValorAPI/Data/Repository/INCVRepository.cs, api/NinosConValorAPI/Data/Repository/NCVRepository.cs, api/NinosConValorAPI/Migrations/20220914224025_HealthReportMigration.Designer.cs, api/NinosConValorAPI/Migrations/20220914224025_HealthReportMigration.cs, api/NinosConValorAPI/Models/HealthReportModel.cs, api/NinosConValorAPI/Program.cs, api/NinosConValorAPI/Services/HealthReportService.cs, api/NinosConValorAPI/Services/IHealthReportService.cs, api/UnitTests/AutomapperUT/AutomapperUT.cs, api/UnitTests/ControllersUT/HealthReportsControllerUT.cs, api/UnitTests/ControllersUT/KidsControllerUT.cs, api/UnitTests/NCVRepositoryUT/HealthReportRepositoryUT.cs, api/UnitTests/ServiceUT/HealthReportServiceUT.cs
@CarolinaAdrianaHidalgoAvila 
@CarolinaMelendez
=> Health report classes added - HealthReportsController tested and working.

.github/workflows/frontend.yml
Implementacion de tests en github actions para verificar que no existen errores en eslint o prettier antes de hacer un push.
=> Verificacion de prettier y eslint

api/NinosConValorAPI/Services/FixedAssetService.cs, api/NinosConValorAPI/Services/IFixedAssetService.cs
Change the language of the code to English instead of Spanish
=> Standardize backend code in fixed assets

api/NinosConValorAPI/Data/NCV_DBContext.cs, api/NinosConValorAPI/Migrations/20220930021201_CreateTableUser.Designer.cs, api/NinosConValorAPI/Migrations/20220930021201_CreateTableUser.cs
Se realizo la migracion para poder crear la Tabla user y poder trabajar en seguridad tanto como front y backend
=> Back end table user

web-ui/src/App.js, web-ui/src/Views/User/CreateUser.js
Se verifico que el formulario de crear usuarios funcione correctamente con el backend y la base de datos (las contraseñas deben ser con texto y numeros  ej:Soporte!23) posteriormente se implementara notificaciones para validacion
=> se verifico el funcionamiento de crear usuario con el backend

web-ui/src/Components/SingleItemCard.jsx, web-ui/src/Views/KidsFiles/ShowOneKidFile.js
Se implemento la componente sin imagen para el reportHealth y se mejoro algunos detalles para del componente singleItemCard
=> Improve health report

api/NinosConValorAPI/Controllers/AuthController.cs, api/NinosConValorAPI/Models/Security/CreateUserRoleViewModel.cs, api/NinosConValorAPI/Program.cs, api/NinosConValorAPI/Services/Security/IUserService.cs, api/NinosConValorAPI/Services/Security/UserService.cs, api/NinosConValorAPI/appsettings.json
Se corrigio el 500 que nos arojaba cuanto intentabamos hacer el login, el error se daba por que el tamaño de contraseña no estaba soportado
=> Se corrigio el error 500 que daba al intentar iniciar secion

web-ui/cypress/e2e/homePage.cy.js, web-ui/src/App.js, web-ui/src/Components/NavBar.jsx, web-ui/src/Views/HomePage/HomePage.css, web-ui/src/Views/HomePage/HomePageForm.js, web-ui/src/Views/Login/LoginForm.js
Se agrego la opcion visible del boton de crear usuario en barra de navegacion y se quitaron los botones
=> Update home page

api/NinosConValorAPI/Controllers/AuthController.cs, api/NinosConValorAPI/Services/Security/IUserService.cs, api/NinosConValorAPI/Services/Security/UserService.cs
Registra el usuario con un rol especifico por el momento dos identificados: AdminUser y AuntUser
=> Add roles to users 

web-ui/cypress/e2e/fixedAssets/showOneKidFile.cy.js, web-ui/cypress/fixtures/fixedAssets/aBasicInfo.json
Por algunas razones inexplicables, solo funciona cuando esta dentro de la carpeta de fixedAssets
=> added basic e2e test of view kid file

api/NinosConValorAPI/Controllers/AuthController.cs, api/NinosConValorAPI/Services/Security/IUserService.cs, api/NinosConValorAPI/Services/Security/UserService.cs, web-ui/src/Views/User/CreateUser.js
Se añadió la opción de poder crear usuarios con el rol  de super usuario en backend y frontend
=> Add super user

api/NinosConValorAPI/Controllers/AuthController.cs, api/NinosConValorAPI/Models/Security/UserBasicInformation.cs, api/NinosConValorAPI/Models/Security/UserBasicInformationModel.cs, api/NinosConValorAPI/Services/Security/IUserService.cs, api/NinosConValorAPI/Services/Security/UserService.cs
=> User list backend

web-ui/package-lock.json, web-ui/src/Views/User/CreateUser.js
Validaciones personalizadas de los campos de createUser
=> Validations

api/NinosConValorAPI/Controllers/FixedAssetsController.cs, api/NinosConValorAPI/Data/Entity/FixedAssetEntity.cs, api/NinosConValorAPI/Models/FixedAssetModel.cs, api/UnitTests/NCVRepositoryUT/FixedAssetUT.cs
Pruebas a los campos de FixedAssetModel y FixedAssetEntity, a través de Postman y también con el uso de xUnit
=> tests passing using Postman and Unit testings checked

api/NinosConValorAPI/Controllers/AuthController.cs, api/NinosConValorAPI/Models/Security/EditUserViewModel.cs, api/NinosConValorAPI/Services/Security/IUserService.cs, api/NinosConValorAPI/Services/Security/UserService.cs
Edit basic user information performed only by the super user
=> Edit user backend

web-ui/src/App.js, web-ui/src/Views/User/EditUser.js
A superuser can select a user from the user list and edit his information
=> Feature Edit User

web-ui/src/Views/User/EditUser.js
Created validations for edit user form
=> Validations edit user

web-ui/src/Views/KidsFiles/ShowOneKidFile.js
Se corrigió el error de que despues de guardar un niño aparezca el popup de querer borrar el file.
=> fixed delete alert after edit confirmation button

web-ui/src/Views/KidsFiles/AddKid.js, web-ui/src/Views/KidsFiles/ShowOneKidFile.js
Agregue la opción de mostrar la edad en Años y en Meses como tienen en la fundación, en caso de que es un recién nacido muestra solo los días y en caso de no tener más de un año muestra solo los meses.
Estaba intentando validar en el formulario que el día máximo a seleccionar en la fecha de nacimiento sea la fecha actual, pero llevo varios intentos y no pude, al final quedó comentado para seguir trabajando luego.
=> Daterefactor

web-ui/cypress/e2e/homePage.cy.js, web-ui/src/Components/NavBar.jsx, web-ui/src/Views/User/EditUser.js
Added button "cancelar" and changed "editar" tu "Guardar"
=> Refactor edit user

web-ui/src/App.js, web-ui/src/Views/User/EditProfile.js, web-ui/src/Views/User/Profile.js
Implemented profile view with edit user information functional
=> Profile view

.github/workflows/frontendDeploy.yml, package-lock.json, web-ui/.firebaserc, web-ui/firebase.json
Se añadio un nuevo sitio para que se pueda deployar en dos ambientes, producción y staging (desarrollo)
=> Separate deploys

api/NinosConValorAPI/AutomapperProfile.cs, api/NinosConValorAPI/Controllers/AssetResponsibleController.cs, api/NinosConValorAPI/Data/Entity/AssetResponsibleEntity.cs, api/NinosConValorAPI/Data/Entity/FixedAssetEntity.cs, api/NinosConValorAPI/Data/NCV_DBContext.cs, api/NinosConValorAPI/Data/Repository/INCVRepository.cs, api/NinosConValorAPI/Data/Repository/NCVRepository.cs, api/NinosConValorAPI/Migrations/20221124025928_AssetResponsibleAdded.Designer.cs, api/NinosConValorAPI/Migrations/20221124025928_AssetResponsibleAdded.cs, api/NinosConValorAPI/Models/AssetResponsibleModel.cs, api/NinosConValorAPI/Models/FixedAssetModel.cs, api/NinosConValorAPI/Program.cs, api/NinosConValorAPI/Services/AssetResponsibleService.cs, api/NinosConValorAPI/Services/FixedAssetService.cs, api/NinosConValorAPI/Services/IAssetResponsibleService.cs, api/UnitTests/ServiceUT/FixedAssetServiceUT.cs
=> Responsible Added In Fixed Asset Backend

web-ui/src/Views/KidsFiles/API/getAxios.js, web-ui/src/Views/KidsFiles/FoundationReport/AddFoundationReport.js
Admission date vs birth date checked
=> Add foundation report  edit health report

web-ui/src/App.js, web-ui/src/Views/FixedAssets/AssetResponsibles/ShowAssetResponsibles.js, web-ui/src/Views/FixedAssets/AssetResponsibles/ShowAssetResponsibles.spec.js, web-ui/src/Views/FixedAssets/CreateFixedAsset.spec.js, web-ui/src/Views/FixedAssets/CreateFixedAssetForm.js, web-ui/src/Views/FixedAssets/ShowFixedAssets.js, web-ui/src/Views/FixedAssets/ShowOneFixedAsset.js, web-ui/src/Views/FixedAssets/UpdateFixedAsset.js
=> Responsible on FrontEnd

web-ui/package-lock.json, web-ui/src/Views/KidsFiles/BasicDataReport/EditKid.js
se puso en required los labels y los labels ya se muestran
=> Labelsformeditar

web-ui/src/Views/KidsFiles/BasicDataReport/EditKid.js
Edit form validates that CI is necessary to be filled in.
=> Validationformedit

web-ui/src/Components/TableBasic.jsx, web-ui/src/Views/KidsFiles/HealthReport/BiometricsReport.js
=> done delete

web-ui/src/Components/TableBasic.jsx
Se arregló el botoncito de delete que no aparezca en los años
=> fixed table buttons delete

web-ui/src/Views/KidsFiles/BasicDataReport/AddKid.js
1) Corregir campos obligatorios, pasan como opcionales (lugar de nacimiento y genero)
=> Correcion registrar nino

web-ui/src/Views/KidsFiles/HealthReport/AddHealthReport.js, web-ui/src/Views/KidsFiles/HealthReport/EditHealthReport.js
1) Corregir marcador de campo vacio a opcional (CI de discapacidad)
=> Correccion vista salud

web-ui/src/Views/KidsFiles/LegalReport/AddLegalReport.js, web-ui/src/Views/KidsFiles/LegalReport/EditLegalReport.js
1) Corregir campos obligatorios y opcionales al mismo tiempo (DNA Y NUREJ)
2) Corregir marcador de campos opcionales a obligatorios al momento de Editar (DNA Y NUREJ)
=> Correccion vista legal

web-ui/src/Views/KidsFiles/EducationReport/AddEducationReport.js, web-ui/src/Views/KidsFiles/EducationReport/EditEducationReport.js
1) Corregir marcador de campo vacio a opcional (Grado Escolar)
2) Corregir marcador de campos opcionales a obligatorios al momento de Editar (UNIDAD EDUCATIVA Y NUREJ)
=> Correccion vista educacion

web-ui/src/Views/User/CreateUser.js
se modificó la validación de correo al momento de crear un usuario para evitar que muestre "correo ya utilizado" sin existir dicho correo.
=> Correccion de mensaje de correo ya existente sin estar registrado en crear usuario

web-ui/cypress/e2e/Login.cy.js
se implementaron pruebas cypress para login
=> implementacion pruebas e2e para login

web-ui/cypress/e2e/Users.cy.js, web-ui/src/Components/NavBar.jsx
se añadieron las pruebas cypress para los accesos de los usuarios y se modifico el componente navbar para agregar los elementos necesarios para las pruebas
=> implementacion de pruebas e2e para accesos de usuarios 

web-ui/cypress/e2e/CreateAssetCategory.cy.js
Pruebas e2e para código corto de categoría
=> E2e asset category

web-ui/cypress/e2e/kids/addKid.cy.js, web-ui/cypress/fixtures/Kids/anKid.json
1) happy path de crear y codigo de estado.
2) validacion de campos obligatorios.
=> E2e crear nino

web-ui/cypress/e2e/fixedAssets/showAssetsByCategory.cy.js
Pruebas e2e para gestionar tipo de categoría en activos fijos.
=> implementacion de pruebas e2e para crear tipos en categoria

web-ui/cypress/e2e/fixedAssets/addAsset.cy.js, web-ui/cypress/fixtures/fixedAssets/anAsset.json
1) happy path de crear y codigo de estado.
2) validacion de campos obligatorios.
=> E2e crear activo fijo

web-ui/cypress/e2e/DeleteAssetCategory.cy.js
Se implementaron pruebas e2e para eliminar categoría con categoría corta
=> E2e delete asset category

web-ui/cypress/e2e/CreateAssetCategory.cy.js
se soluciono el error de e2e cypress
=> solucion error en e2e test git
